interface ZIF_IM_I_COVID_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZIM_I_COVID,
 CREATE_ZIM_I_COVID             TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAAEAFBAB51D7C516',
 DELETE_ZIM_I_COVID             TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAAEAFBAB51D84516',
 LOCK_ZIM_I_COVID               TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAAEAFBAB51D70516',
 SAVE_ZIM_I_COVID               TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAAEAFBAB51D8C516',
 UNLOCK_ZIM_I_COVID             TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAAEAFBAB51D74516',
 UPDATE_ZIM_I_COVID             TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAAEAFBAB51D80516',
 VALIDATE_ZIM_I_COVID           TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAAEAFBAB51D88516',
      END OF ZIM_I_COVID,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZIM_I_COVID,
        BEGIN OF LOCK_ZIM_I_COVID,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZIM_I_COVID,
        BEGIN OF UNLOCK_ZIM_I_COVID,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZIM_I_COVID,
      END OF ZIM_I_COVID,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZIM_I_COVID,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAAAEAFBAB51DA0516',
      END OF ZIM_I_COVID,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZIM_I_COVID,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAAEAFBAB51D6E516',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAAEAFBAB51D6A516',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAAEAFBAB51D7A516',
      END OF ZIM_I_COVID,
      BEGIN OF ZIM_I_COVID_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAAEAFBAB51D92516',
      END OF ZIM_I_COVID_LOCK,
      BEGIN OF ZIM_I_COVID_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAAEAFBAB51D90516',
      END OF ZIM_I_COVID_MESSAGE,
      BEGIN OF ZIM_I_COVID_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAAEAFBAB51D94516',
      END OF ZIM_I_COVID_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZIM_I_COVID,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZIM_I_COVID,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C299270591EDAAAEAFBAB51D60516' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZIM_I_COVID' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZIM_I_COVID,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAAEAFBAB51DA2516',
      END OF ZIM_I_COVID,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZIM_I_COVID                    TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAAEAFBAB51D64516',
 ZIM_I_COVID_LOCK               TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAAEAFBAB51D6C516',
 ZIM_I_COVID_MESSAGE            TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAAEAFBAB51D68516',
 ZIM_I_COVID_PROPERTY           TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAAEAFBAB51D78516',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZIM_I_COVID,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  COUNTRY                        TYPE STRING VALUE 'COUNTRY',
  CONFIRMED                      TYPE STRING VALUE 'CONFIRMED',
  RECOVERED                      TYPE STRING VALUE 'RECOVERED',
  DECEASED                       TYPE STRING VALUE 'DECEASED',
      END OF ZIM_I_COVID,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZIM_I_COVID,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C299270591EDAAAEAFBAB51D66516',
      END OF ZIM_I_COVID,
    END OF SC_NODE_CATEGORY .
endinterface.
