interface ZIF_IM_I_PARTIDASK_BOPF_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E588E52D',
 CREATE_ZIM_I_PARTIDASK_BOPF    TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E586052D',
 DELETE_ZIM_I_PARTIDASK_BOPF    TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E586852D',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E588C52D',
 LOCK_ZIM_I_PARTIDASK_BOPF      TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E585452D',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E589252D',
 SAVE_ZIM_I_PARTIDASK_BOPF      TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E587052D',
 UNLOCK_ZIM_I_PARTIDASK_BOPF    TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E585852D',
 UPDATE_ZIM_I_PARTIDASK_BOPF    TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E586452D',
 VALIDATE_ZIM_I_PARTIDASK_BOPF  TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E586C52D',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAEDCE574E589052D',
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZIM_I_PARTIDASK_BOPF,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_ZIM_I_PARTIDASK_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZIM_I_PARTIDASK_BOPF,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_ZIM_I_PARTIDASK_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZIM_I_PARTIDASK_BOPF,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAAEDCE574E588852D',
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAAEDCE574E588A52D',
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAEDCE574E585252D',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAEDCE574E584E52D',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAEDCE574E585E52D',
      END OF ZIM_I_PARTIDASK_BOPF,
      BEGIN OF ZIM_I_PARTIDASK_BOPF_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAEDCE574E587652D',
      END OF ZIM_I_PARTIDASK_BOPF_LOCK,
      BEGIN OF ZIM_I_PARTIDASK_BOPF_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAEDCE574E587452D',
      END OF ZIM_I_PARTIDASK_BOPF_MESSAGE,
      BEGIN OF ZIM_I_PARTIDASK_BOPF_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAEDCE574E587852D',
      END OF ZIM_I_PARTIDASK_BOPF_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C299270591EDAAEDCE574E584452D' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZIM_I_PARTIDASK_BOPF' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E589452D',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E589652D',
 DELETE_DRAFT_WHN_ACTIVE_DELETE TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E58A452D',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E58A252D',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E58A052D',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E589E52D',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E589852D',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E589C52D',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAEDCE574E589A52D',
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '000C299270591EDAAEDCE574E587C52D',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZIM_I_PARTIDASK_BOPF           TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAEDCE574E584852D',
 ZIM_I_PARTIDASK_BOPF_LOCK      TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAEDCE574E585052D',
 ZIM_I_PARTIDASK_BOPF_MESSAGE   TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAEDCE574E584C52D',
 ZIM_I_PARTIDASK_BOPF_PROPERTY  TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAEDCE574E585C52D',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID_PARTIDA                     TYPE STRING VALUE 'ID_PARTIDA',
  DATA_PARTIDA                   TYPE STRING VALUE 'DATA_PARTIDA',
  ID_RODADA                      TYPE STRING VALUE 'ID_RODADA',
  ID_ESTADIO                     TYPE STRING VALUE 'ID_ESTADIO',
  PUBLICO                        TYPE STRING VALUE 'PUBLICO',
  RENDA                          TYPE STRING VALUE 'RENDA',
  MOEDA                          TYPE STRING VALUE 'MOEDA',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C299270591EDAAEDCE574E584A52D',
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '000C299270591EDAAEDCE574E587A52D',
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZIM_I_PARTIDASK_BOPF,
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '000C299270591EDAAEDCE574E58A652D',
      END OF ZIM_I_PARTIDASK_BOPF,
    END OF SC_VALIDATION .
endinterface.
