interface ZIF_IM_I_ESTADIOS_BOPF_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZIM_I_ESTADIOS_BOPF,
 CREATE_ZIM_I_ESTADIOS_BOPF     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAC8171F2E073E51B',
 DELETE_ZIM_I_ESTADIOS_BOPF     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAC8171F2E074651B',
 LOCK_ZIM_I_ESTADIOS_BOPF       TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAC8171F2E073251B',
 SAVE_ZIM_I_ESTADIOS_BOPF       TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAC8171F2E074E51B',
 UNLOCK_ZIM_I_ESTADIOS_BOPF     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAC8171F2E073651B',
 UPDATE_ZIM_I_ESTADIOS_BOPF     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAC8171F2E074251B',
 VALIDATE_ZIM_I_ESTADIOS_BOPF   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAAC8171F2E074A51B',
      END OF ZIM_I_ESTADIOS_BOPF,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZIM_I_ESTADIOS_BOPF,
        BEGIN OF LOCK_ZIM_I_ESTADIOS_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZIM_I_ESTADIOS_BOPF,
        BEGIN OF UNLOCK_ZIM_I_ESTADIOS_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZIM_I_ESTADIOS_BOPF,
      END OF ZIM_I_ESTADIOS_BOPF,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZIM_I_ESTADIOS_BOPF,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAAC8171F2E076251B',
      END OF ZIM_I_ESTADIOS_BOPF,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZIM_I_ESTADIOS_BOPF,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAC8171F2E073051B',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAC8171F2E072C51B',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAC8171F2E073C51B',
      END OF ZIM_I_ESTADIOS_BOPF,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAC8171F2E075451B',
      END OF ZIM_I_ESTADIOS_BOPF_LOCK,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAC8171F2E075251B',
      END OF ZIM_I_ESTADIOS_BOPF_MESSAGE,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAAC8171F2E075651B',
      END OF ZIM_I_ESTADIOS_BOPF_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZIM_I_ESTADIOS_BOPF,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZIM_I_ESTADIOS_BOPF,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C299270591EDAAC8171F2E072251B' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZIM_I_ESTADIOS_BOPF' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZIM_I_ESTADIOS_BOPF,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C299270591EDAAC8171F2E076451B',
      END OF ZIM_I_ESTADIOS_BOPF,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZIM_I_ESTADIOS_BOPF            TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAC8171F2E072651B',
 ZIM_I_ESTADIOS_BOPF_LOCK       TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAC8171F2E072E51B',
 ZIM_I_ESTADIOS_BOPF_MESSAGE    TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAC8171F2E072A51B',
 ZIM_I_ESTADIOS_BOPF_PROPERTY   TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAAC8171F2E073A51B',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZIM_I_ESTADIOS_BOPF,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID_ESTADIO                     TYPE STRING VALUE 'ID_ESTADIO',
  NOMEESTADIO                    TYPE STRING VALUE 'NOMEESTADIO',
  CAPACIDADE                     TYPE STRING VALUE 'CAPACIDADE',
      END OF ZIM_I_ESTADIOS_BOPF,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZIM_I_ESTADIOS_BOPF,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C299270591EDAAC8171F2E072851B',
      END OF ZIM_I_ESTADIOS_BOPF,
    END OF SC_NODE_CATEGORY .
endinterface.
