interface ZIF_DEMO_I_SALESORDER_TX_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZDEMO_I_SALESORDER_TX,
 CREATE_ZDEMO_I_SALESORDER_TX   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA23648066EE516',
 DELETE_ZDEMO_I_SALESORDER_TX   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA23648066F6516',
 LOCK_ZDEMO_I_SALESORDER_TX     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA23648066E2516',
 SAVE_ZDEMO_I_SALESORDER_TX     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA23648066FE516',
 UNLOCK_ZDEMO_I_SALESORDER_TX   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA23648066E6516',
 UPDATE_ZDEMO_I_SALESORDER_TX   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA23648066F2516',
 VALIDATE_ZDEMO_I_SALESORDER_TX TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA23648066FA516',
      END OF ZDEMO_I_SALESORDER_TX,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZDEMO_I_SALESORDER_TX,
        BEGIN OF LOCK_ZDEMO_I_SALESORDER_TX,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZDEMO_I_SALESORDER_TX,
        BEGIN OF UNLOCK_ZDEMO_I_SALESORDER_TX,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZDEMO_I_SALESORDER_TX,
      END OF ZDEMO_I_SALESORDER_TX,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZDEMO_I_SALESORDER_TX,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAABA2364806712516',
      END OF ZDEMO_I_SALESORDER_TX,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZDEMO_I_SALESORDER_TX,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA23648066E0516',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA23648066DC516',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA23648066EC516',
      END OF ZDEMO_I_SALESORDER_TX,
      BEGIN OF ZDEMO_I_SALESORDER_TX_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA2364806704516',
      END OF ZDEMO_I_SALESORDER_TX_LOCK,
      BEGIN OF ZDEMO_I_SALESORDER_TX_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA2364806702516',
      END OF ZDEMO_I_SALESORDER_TX_MESSAGE,
      BEGIN OF ZDEMO_I_SALESORDER_TX_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA2364806706516',
      END OF ZDEMO_I_SALESORDER_TX_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZDEMO_I_SALESORDER_TX,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZDEMO_I_SALESORDER_TX,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C299270591EDAABA23648066D2516' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZDEMO_I_SALESORDER_TX' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZDEMO_I_SALESORDER_TX,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C299270591EDAABA2364806714516',
      END OF ZDEMO_I_SALESORDER_TX,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZDEMO_I_SALESORDER_TX          TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA23648066D6516',
 ZDEMO_I_SALESORDER_TX_LOCK     TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA23648066DE516',
 ZDEMO_I_SALESORDER_TX_MESSAGE  TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA23648066DA516',
 ZDEMO_I_SALESORDER_TX_PROPERTY TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA23648066EA516',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZDEMO_I_SALESORDER_TX,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  SALESORDER                     TYPE STRING VALUE 'SALESORDER',
  BUSINESSPARTNER                TYPE STRING VALUE 'BUSINESSPARTNER',
  CURRENCYCODE                   TYPE STRING VALUE 'CURRENCYCODE',
  GROSSAMOUNT                    TYPE STRING VALUE 'GROSSAMOUNT',
  NETAMOUNT                      TYPE STRING VALUE 'NETAMOUNT',
  BILLINGSTATUS                  TYPE STRING VALUE 'BILLINGSTATUS',
  OVERALLSTATUS                  TYPE STRING VALUE 'OVERALLSTATUS',
  CREA_DATE_TIME                 TYPE STRING VALUE 'CREA_DATE_TIME',
  CREA_UNAME                     TYPE STRING VALUE 'CREA_UNAME',
  LCHG_DATE_TIME                 TYPE STRING VALUE 'LCHG_DATE_TIME',
  LCHG_UNAME                     TYPE STRING VALUE 'LCHG_UNAME',
      END OF ZDEMO_I_SALESORDER_TX,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZDEMO_I_SALESORDER_TX,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C299270591EDAABA23648066D8516',
      END OF ZDEMO_I_SALESORDER_TX,
    END OF SC_NODE_CATEGORY .
endinterface.
