interface ZIF_IM_I_ESTADIOS_NEW_BOPF_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
 CREATE_ZIM_I_ESTADIOS_NEW_BOPF TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADB028F34E8B2525',
 DELETE_ZIM_I_ESTADIOS_NEW_BOPF TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADB028F34E8BA525',
 LOCK_ZIM_I_ESTADIOS_NEW_BOPF   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADB028F34E8A6525',
 SAVE_ZIM_I_ESTADIOS_NEW_BOPF   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADB028F34E8C2525',
 UNLOCK_ZIM_I_ESTADIOS_NEW_BOPF TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADB028F34E8AA525',
 UPDATE_ZIM_I_ESTADIOS_NEW_BOPF TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADB028F34E8B6525',
 VALIDATE_ZIM_I_ESTADIOS_NEW_BO TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADB028F34E8BE525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
        BEGIN OF LOCK_ZIM_I_ESTADIOS_NEW_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZIM_I_ESTADIOS_NEW_BOPF,
        BEGIN OF UNLOCK_ZIM_I_ESTADIOS_NEW_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZIM_I_ESTADIOS_NEW_BOPF,
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAADB028F34E8D6525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADB028F34E8A4525',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADB028F34E8A0525',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADB028F34E8B0525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADB028F34E8C8525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF_LOCK,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF_MESSAG,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADB028F34E8C6525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF_MESSAG,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF_PROPER,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADB028F34E8CA525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF_PROPER,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C299270591EDAADB028F34E896525' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZIM_I_ESTADIOS_NEW_BOPF' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C299270591EDAADB028F34E8D8525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZIM_I_ESTADIOS_NEW_BOPF        TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADB028F34E89A525',
 ZIM_I_ESTADIOS_NEW_BOPF_LOCK   TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADB028F34E8A2525',
 ZIM_I_ESTADIOS_NEW_BOPF_MESSAG TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADB028F34E89E525',
 ZIM_I_ESTADIOS_NEW_BOPF_PROPER TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADB028F34E8AE525',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID_ESTADIO                     TYPE STRING VALUE 'ID_ESTADIO',
  NOME_ESTADIO                   TYPE STRING VALUE 'NOME_ESTADIO',
  CIDADE                         TYPE STRING VALUE 'CIDADE',
  UF                             TYPE STRING VALUE 'UF',
  CAPACIDADE                     TYPE STRING VALUE 'CAPACIDADE',
  GEOCODE                        TYPE STRING VALUE 'GEOCODE',
  LATITUDE                       TYPE STRING VALUE 'LATITUDE',
  LONGITUDE                      TYPE STRING VALUE 'LONGITUDE',
  CREATED_AT                     TYPE STRING VALUE 'CREATED_AT',
  CREATED_BY                     TYPE STRING VALUE 'CREATED_BY',
  CHANGED_AT                     TYPE STRING VALUE 'CHANGED_AT',
  CHANGED_BY                     TYPE STRING VALUE 'CHANGED_BY',
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZIM_I_ESTADIOS_NEW_BOPF,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C299270591EDAADB028F34E89C525',
      END OF ZIM_I_ESTADIOS_NEW_BOPF,
    END OF SC_NODE_CATEGORY .
endinterface.
