interface ZIF_IM_I_ESTADIOS_BOPF_TOTAL_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
 CREATE_ZIM_I_ESTADIOS_BOPF_TOT TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADAEDF06F8654525',
 DELETE_ZIM_I_ESTADIOS_BOPF_TOT TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADAEDF06F865C525',
 LOCK_ZIM_I_ESTADIOS_BOPF_TOTAL TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADAEDF06F8648525',
 SAVE_ZIM_I_ESTADIOS_BOPF_TOTAL TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADAEDF06F8664525',
 UNLOCK_ZIM_I_ESTADIOS_BOPF_TOT TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADAEDF06F864C525',
 UPDATE_ZIM_I_ESTADIOS_BOPF_TOT TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADAEDF06F8658525',
 VALIDATE_ZIM_I_ESTADIOS_BOPF_T TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAADAEDF06F8660525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
        BEGIN OF LOCK_ZIM_I_ESTADIOS_BOPF_TOTAL,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZIM_I_ESTADIOS_BOPF_TOTAL,
        BEGIN OF UNLOCK_ZIM_I_ESTADIOS_BOPF_TOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZIM_I_ESTADIOS_BOPF_TOT,
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAADAEDF06F8678525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADAEDF06F8646525',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADAEDF06F8642525',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADAEDF06F8652525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADAEDF06F866A525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL_LOCK,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL_MESS,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADAEDF06F8668525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL_MESS,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL_PROP,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAADAEDF06F866C525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL_PROP,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C299270591EDAADAEDF06F8638525' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZIM_I_ESTADIOS_BOPF_TOTAL' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C299270591EDAADAEDF06F867A525',
 ADMINISTRATIVE_DATA            TYPE /BOBF/DET_KEY VALUE '000C299270591EDAADAF873F5DC18525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZIM_I_ESTADIOS_BOPF_TOTAL      TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADAEDF06F863C525',
 ZIM_I_ESTADIOS_BOPF_TOTAL_LOCK TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADAEDF06F8644525',
 ZIM_I_ESTADIOS_BOPF_TOTAL_MESS TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADAEDF06F8640525',
 ZIM_I_ESTADIOS_BOPF_TOTAL_PROP TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAADAEDF06F8650525',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID_ESTADIO                     TYPE STRING VALUE 'ID_ESTADIO',
  NOME_ESTADIO                   TYPE STRING VALUE 'NOME_ESTADIO',
  CIDADE                         TYPE STRING VALUE 'CIDADE',
  UF                             TYPE STRING VALUE 'UF',
  CAPACIDADE                     TYPE STRING VALUE 'CAPACIDADE',
  GEOCODE                        TYPE STRING VALUE 'GEOCODE',
  LATITUDE                       TYPE STRING VALUE 'LATITUDE',
  LONGITUDE                      TYPE STRING VALUE 'LONGITUDE',
  CREATED_AT                     TYPE STRING VALUE 'CREATED_AT',
  CREATED_BY                     TYPE STRING VALUE 'CREATED_BY',
  CHANGED_AT                     TYPE STRING VALUE 'CHANGED_AT',
  CHANGED_BY                     TYPE STRING VALUE 'CHANGED_BY',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZIM_I_ESTADIOS_BOPF_TOTAL,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C299270591EDAADAEDF06F863E525',
      END OF ZIM_I_ESTADIOS_BOPF_TOTAL,
    END OF SC_NODE_CATEGORY .
endinterface.
