interface ZIF_IM_I_PARTIDAS_VIEW_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZIM_I_PARTIDAS_VIEW,
 CREATE_ZIM_I_PARTIDAS_VIEW     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA3C95B5208E516',
 DELETE_ZIM_I_PARTIDAS_VIEW     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA3C95B52096516',
 LOCK_ZIM_I_PARTIDAS_VIEW       TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA3C95B52082516',
 SAVE_ZIM_I_PARTIDAS_VIEW       TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA3C95B5209E516',
 UNLOCK_ZIM_I_PARTIDAS_VIEW     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA3C95B52086516',
 UPDATE_ZIM_I_PARTIDAS_VIEW     TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA3C95B52092516',
 VALIDATE_ZIM_I_PARTIDAS_VIEW   TYPE /BOBF/ACT_KEY VALUE '000C299270591EDAABA3C95B5209A516',
      END OF ZIM_I_PARTIDAS_VIEW,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZIM_I_PARTIDAS_VIEW,
        BEGIN OF LOCK_ZIM_I_PARTIDAS_VIEW,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZIM_I_PARTIDAS_VIEW,
        BEGIN OF UNLOCK_ZIM_I_PARTIDAS_VIEW,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZIM_I_PARTIDAS_VIEW,
      END OF ZIM_I_PARTIDAS_VIEW,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZIM_I_PARTIDAS_VIEW,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000C299270591EDAABA3C95B520B2516',
      END OF ZIM_I_PARTIDAS_VIEW,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZIM_I_PARTIDAS_VIEW,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA3C95B52080516',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA3C95B5207C516',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA3C95B5208C516',
      END OF ZIM_I_PARTIDAS_VIEW,
      BEGIN OF ZIM_I_PARTIDAS_VIEW_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA3C95B520A4516',
      END OF ZIM_I_PARTIDAS_VIEW_LOCK,
      BEGIN OF ZIM_I_PARTIDAS_VIEW_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA3C95B520A2516',
      END OF ZIM_I_PARTIDAS_VIEW_MESSAGE,
      BEGIN OF ZIM_I_PARTIDAS_VIEW_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C299270591EDAABA3C95B520A6516',
      END OF ZIM_I_PARTIDAS_VIEW_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZIM_I_PARTIDAS_VIEW,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZIM_I_PARTIDAS_VIEW,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C299270591EDAABA3C95B52072516' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZIM_I_PARTIDAS_VIEW' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZIM_I_PARTIDAS_VIEW,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000C299270591EDAABA3C95B520B4516',
      END OF ZIM_I_PARTIDAS_VIEW,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZIM_I_PARTIDAS_VIEW            TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA3C95B52076516',
 ZIM_I_PARTIDAS_VIEW_LOCK       TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA3C95B5207E516',
 ZIM_I_PARTIDAS_VIEW_MESSAGE    TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA3C95B5207A516',
 ZIM_I_PARTIDAS_VIEW_PROPERTY   TYPE /BOBF/OBM_NODE_KEY VALUE '000C299270591EDAABA3C95B5208A516',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZIM_I_PARTIDAS_VIEW,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID_RODADA                      TYPE STRING VALUE 'ID_RODADA',
  ID_PARTIDA                     TYPE STRING VALUE 'ID_PARTIDA',
  ID_ESTADIO                     TYPE STRING VALUE 'ID_ESTADIO',
  ID_TIME_A                      TYPE STRING VALUE 'ID_TIME_A',
  ID_TIME_B                      TYPE STRING VALUE 'ID_TIME_B',
  PUBLICO                        TYPE STRING VALUE 'PUBLICO',
  RENDA                          TYPE STRING VALUE 'RENDA',
  MOEDA                          TYPE STRING VALUE 'MOEDA',
  DATA                           TYPE STRING VALUE 'DATA',
  PLACAR_TIME_A                  TYPE STRING VALUE 'PLACAR_TIME_A',
  PLACAR_TIME_B                  TYPE STRING VALUE 'PLACAR_TIME_B',
      END OF ZIM_I_PARTIDAS_VIEW,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZIM_I_PARTIDAS_VIEW,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C299270591EDAABA3C95B52078516',
      END OF ZIM_I_PARTIDAS_VIEW,
    END OF SC_NODE_CATEGORY .
endinterface.
